### ISSUE TITLE
Possible Problem with Django Version 4

### ISSUE THREAD

**Issue by tobiasschweizer** [lambdamusic/Ontospy#112]
Hi 

I have installed Ontospy with Django (and Pygments):

```
Django             4.0.1
```

Then I tried to generate the docs using `gendocs` with option 2 "Html: multi page" which failed:

> Traceback (most recent call last):
  File ".../env/lib/python3.9/site-packages/django/template/base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'ifequal'

I was able to fix this problem by doing `pip3 install django<4`

I think this isn't a bug but rather something that would be good to go in https://github.com/lambdamusic/Ontospy/blob/534e408372edd392590e12839c32a403430aac23/requirements.txt#L11

**Comment by lambdamusic** [comment]
Yes I noticed that the recent Django version breaks some of the template tags in Ontospy.

I'll change the requirements file.

Also FYI I'm planning to drop django altogether in the future and use a templating library with a smaller footprint eg jinja so that it'll be easier to manage in the long run

**Comment by lambdamusic** [comment]
Django dropped as of [Ontospy 2.0](https://github.com/lambdamusic/Ontospy/releases/tag/v2.0.0)
